In [17]:
import pandas as pd

csv = "Data/Behavioral_Risk_2011_clean.csv"

tobacco_df = pd.read_csv(csv)
tobacco_df.head()

,YEAR,LocationAbbr,LocationDesc,TopicType,TopicDesc,MeasureDesc,DataSource,Response,Data_Value_Unit,Data_Value_Type,...,Data_Value_Footnote,Data_Value_Std_Err,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,Gender,Race,Age,Education,GeoLocation
0,2018,KY,Kentucky,Tobacco Use – Survey Data,Cigarette Use (Adults),Smoking Status,BRFSS,Current,%,Percentage,...,NaN,2.1,25.3,33.5,1144.0,Female,All Races,18 to 44 Years,All Grades,"(37.645970271000465, -84.77497104799966)"
1,2018,CO,Colorado,Tobacco Use – Survey Data,Cigarette Use (Adults),Smoking Status,BRFSS,Current,%,Percentage,...,NaN,0.6,11.1,13.7,4201.0,Female,All Races,All Ages,All Grades,"(38.843840757000464, -106.13361092099967)"
2,2018,DC,District of Columbia,Tobacco Use – Survey Data,Cigarette Use (Adults),Smoking Status,BRFSS,Current,%,Percentage,...,NaN,1.0,10.6,14.6,2271.0,Female,All Races,All Ages,All Grades,"(38.89037138500049, -77.03196112699965)"
3,2018,WI,Wisconsin,Tobacco Use – Survey Data,Cigarette Use (Adults),Smoking Status,BRFSS,Current,%,Percentage,...,NaN,1.8,13.0,20.0,614.0,Female,All Races,18 to 44 Years,All Grades,"(44.39319117400049, -89.81637074199966)"
4,2018,GA,Georgia,Tobacco Use – Survey Data,Cigarette Use (Adults),Smoking Status,BRFSS,Current,%,Percentage,...,NaN,0.7,13.3,15.9,4918.0,Female,All Races,All Ages,All Grades,"(32.83968109300048, -83.62758034599966)"

In [42]:
df_start = tobacco_df.filter(['YEAR', 'TopicDesc', 'MeasureDesc', 'Response', 'Data_Value', 'Sample_Size', 'Gender'])
df_start['Data_Value'].astype(float)
df_start['Sample_Size'].astype(float)
df_start['Reponse Number'] = gender_start.Data_Value * (gender_start.Sample_Size / 100)
df_start

,YEAR,TopicDesc,MeasureDesc,Response,Data_Value,Sample_Size,Gender,Reponse Number
0,2018,Cigarette Use (Adults),Smoking Status,Current,29.4,1144.0,Female,336.336
1,2018,Cigarette Use (Adults),Smoking Status,Current,12.4,4201.0,Female,520.924
2,2018,Cigarette Use (Adults),Smoking Status,Current,12.6,2271.0,Female,286.146
3,2018,Cigarette Use (Adults),Smoking Status,Current,16.5,614.0,Female,101.310
4,2018,Cigarette Use (Adults),Smoking Status,Current,14.6,4918.0,Female,718.028
...,...,...,...,...,...,...,...,...
33321,2011,Smokeless Tobacco Use (Adults),Smoking Status,Not Current,92.9,4733.0,Overall,NaN
33322,2011,Smokeless Tobacco Use (Adults),Smoking Status,Not Current,92.0,8904.0,Overall,NaN
33323,2011,Smokeless Tobacco Use (Adults),Smoking Status,Not Current,95.2,6072.0,Overall,NaN
33324,2011,Smokeless Tobacco Use (Adults),Smoking Status,Not Current,97.0,12661.0,Overall,NaN
33325,2011,Smokeless Tobacco Use (Adults),Smoking Status,Not Current,97.2,13223.0,Overall,NaN

In [43]:
gender_start = df_start
gender_start = gender_start[gender_start.MeasureDesc !="Frequency of Use"]
gender_start = gender_start[gender_start.Gender !="Overall"]
gender_start = gender_start[gender_start.Response !="Not Current"]
gender_start = gender_start[gender_start.Response !="Former"]
gender_start = gender_start[gender_start.Response !="Never"]
gender_group = gender_start.groupby(['YEAR', 'Response', 'Gender']).agg({'Data_Value': ['mean']})
gender_group

                     Data_Value
                           mean
YEAR Response Gender
2011 Current  Female  10.638679
              Male    15.816038
2012 Current  Female   9.923585
              Male    14.816038
2013 Current  Female   9.627673
              Male    14.725472
2014 Current  Female   9.317296
              Male    14.013208
2015 Current  Female   8.853459
              Male    13.865094
2016 Current  Female   7.123061
              Male    10.938994
2017 Current  Female   7.137526
              Male    10.871698
2018 Current  Female   7.554916
              Male    11.510072

In [44]:
type_df = df_start
type_df = type_df.groupby(['YEAR', 'TopicDesc', 'Response', 'Gender']).agg({'Data_Value': ['mean']})

type_df

                                                        Data_Value
                                                              mean
YEAR TopicDesc                      Response    Gender
2011 Cigarette Use (Adults)         Current     Female   20.200629
                                                Male     23.743396
                                                Overall  22.958576
                                    Every Day   Female   73.562264
                                                Male     71.435849
...                                                            ...
2018 Smokeless Tobacco Use (Adults) Not Current Male     92.447170
                                                Overall  95.709259
                                    Some Days   Female   60.600000
                                                Male     44.164000
                                                Overall  47.190385

[261 rows x 1 columns]

In [49]:
freq_start = df_start

freq_start = freq_start[freq_start.MeasureDesc !="Smoking Status"]
freq_start = freq_start[freq_start.MeasureDesc !="Percent of Former Smokers Among Ever Smokers"]
freq_start = freq_start[freq_start.MeasureDesc !="Quit Attempt in Past Year Among Every Day Cigarette Smokers"]

freq_start = freq_start.groupby(['YEAR', 'TopicDesc', 'MeasureDesc', 'Response']).agg({'Data_Value': ['mean']})
freq_start

                                                               Data_Value
                                                                     mean
YEAR TopicDesc                      MeasureDesc      Response
2011 Cigarette Use (Adults)         Frequency of Use Every Day  72.473585
                                                     Some Days  27.526415
     Smokeless Tobacco Use (Adults) Frequency of Use Every Day  49.108000
                                                     Some Days  50.892000
2012 Cigarette Use (Adults)         Frequency of Use Every Day  71.274214
                                                     Some Days  28.725786
     Smokeless Tobacco Use (Adults) Frequency of Use Every Day  50.984211
                                                     Some Days  49.015789
2013 Cigarette Use (Adults)         Frequency of Use Every Day  71.208805
                                                     Some Days  28.791195
     Smokeless Tobacco Use (Adults) Frequency of Use Every Day  51.238843
                                                     Some Days  48.761157
2014 Cigarette Use (Adults)         Frequency of Use Every Day  70.056604
                                                     Some Days  29.943396
     Smokeless Tobacco Use (Adults) Frequency of Use Every Day  51.598305
                                                     Some Days  48.401695
2015 Cigarette Use (Adults)         Frequency of Use Every Day  69.831447
                                                     Some Days  30.168553
     Smokeless Tobacco Use (Adults) Frequency of Use Every Day  50.053043
                                                     Some Days  49.946957
2016 Cigarette Use (Adults)         Frequency of Use Every Day  69.495597
                                                     Some Days  30.504403
     E-Cigarette Use (Adults)       Frequency of Use Every Day  32.256954
                                                     Some Days  67.743046
     Smokeless Tobacco Use (Adults) Frequency of Use Every Day  51.700000
                                                     Some Days  48.300000
2017 Cigarette Use (Adults)         Frequency of Use Every Day  68.888679
                                                     Some Days  31.111321
     E-Cigarette Use (Adults)       Frequency of Use Every Day  36.191333
                                                     Some Days  63.808667
     Smokeless Tobacco Use (Adults) Frequency of Use Every Day  50.841880
                                                     Some Days  49.158120
2018 Cigarette Use (Adults)         Frequency of Use Every Day  69.866667
                                                     Some Days  30.133333
     E-Cigarette Use (Adults)       Frequency of Use Every Day  37.855208
                                                     Some Days  62.144792
     Smokeless Tobacco Use (Adults) Frequency of Use Every Day  52.609565
                                                     Some Days  47.390435